name: Build CI with Maven
run-name: Build the project by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml